# Default values for ppe-web-${webapp-name}.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
 
replicaCount: 3
 
image:
  repository: 798283861836.dkr.ecr.eu-west-1.amazonaws.com/ppe-web-${webapp-name}
  tag: master
  pullPolicy: Always
 
newrelic:
  enabled: true
 
managementPort: 4000
 
service:
  type: ClusterIP
  port: 4000
 
ingress:
  enabled: true
  tls:
    enabled: true
  backend:
    enabled: false
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/use-port-in-redirects: "true"
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-filter: modPath("^/web/ppe-web-${webapp-name}/", "/")
    zalando.org/aws-load-balancer-scheme: internal
 
global:
  ingress:
    host: sit.ppe-np.elsevier.net
 
debug:
  enabled: false

controller:
  autoscaling:
    averageUtilizationCPUPercentage: 80

resources:
  enabled: true
  requests:
    memory: 500Mi
    cpu: 300m
  limits:
    cpu: 600m
    memory: 500Mi

podDisruptionBudget:
  enabled: true
  # Uncomment only one of the following when enabled is set to true. Do not set any of these values to zero or 100%, this will send kubernetes operator into an infinite loop
  # maxUnavailable: "25%"
  minAvailable: 1
